[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[window]
# opacity = 0.95

[bell]
command = "None"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"  # Send SIGINT

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"  # Ctrl+Backspace = delete word

[env]
TERM = "xterm-256color"

[colors.primary]
background = "0x161718"
foreground = "0xc4c8c5"

[colors.cursor]
text = "0x161718"       # selection_foreground
cursor = "0xd0d0d0"

[colors.selection]
text = "0x161718"       # selection_foreground
background = "0x444444"

[colors.normal]
black   = "0x000000"     # color0
red     = "0xfc5ef0"     # color1
green   = "0x86c38a"     # color2
yellow  = "0xffd6b1"     # color3
blue    = "0x85befd"     # color4
magenta = "0xb9b5fc"     # color5
cyan    = "0x85befd"     # color6
white   = "0xdfdfdf"     # color7


[colors.bright]
black   = "0x000000"     # color8
red     = "0xfc5ef0"     # color9
green   = "0x94f936"     # color10
yellow  = "0xf5ffa7"     # color11
blue    = "0x95cbfe"     # color12
magenta = "0xb9b5fc"     # color13
cyan    = "0x85befd"     # color14
white   = "0xdfdfdf"     # color15
