-- /home/aditya/.config/koreader/settings/profiles.lua
return {
	["EPUB-Widescreen"] = {
		["b_page_margin"] = 15,
		["block_rendering_mode"] = 3,
		["embedded_css"] = true,
		["embedded_fonts"] = true,
		["font_base_weight"] = -0.5,
		["font_gamma"] = 10,
		["font_hinting"] = 2,
		["font_kerning"] = 3,
		["font_size"] = 20,
		["h_page_margins"] = {
			[1] = 140,
			[2] = 140,
		},
		["line_spacing"] = 90,
		["nightmode_images"] = true,
		["render_dpi"] = 96,
		["rotation_mode"] = 0,
		["set_font"] = "Noto Serif",
		["settings"] = {
			["name"] = "EPUB-Widescreen",
			["order"] = {
				[1] = "rotation_mode",
				[2] = "set_font",
				[3] = "font_size",
				[4] = "font_gamma",
				[5] = "font_base_weight",
				[6] = "font_hinting",
				[7] = "font_kerning",
				[8] = "word_spacing",
				[9] = "word_expansion",
				[10] = "visible_pages",
				[11] = "h_page_margins",
				[12] = "t_page_margin",
				[13] = "b_page_margin",
				[14] = "sync_t_b_page_margins",
				[15] = "view_mode",
				[16] = "block_rendering_mode",
				[17] = "render_dpi",
				[18] = "line_spacing",
				[19] = "embedded_css",
				[20] = "embedded_fonts",
				[21] = "smooth_scaling",
				[22] = "nightmode_images",
				[23] = "status_line",
			},
		},
		["smooth_scaling"] = false,
		["status_line"] = 1,
		["sync_t_b_page_margins"] = false,
		["t_page_margin"] = 15,
		["view_mode"] = "page",
		["visible_pages"] = 1,
		["word_expansion"] = 0,
		["word_spacing"] = {
			[1] = 95,
			[2] = 75,
		},
	},
	["PDF-Widescreen"] = {
		["columns"] = 1,
		["contrast"] = 1,
		["font_size"] = 23,
		["gamma"] = 1,
		["hyphenation"] = true,
		["justification"] = true,
		["line_spacing"] = 1.42,
		["page_margins"] = {
			["bottom"] = 0.08,
			["left"] = 0.24,
			["right"] = 0.24,
			["top"] = 0.08,
		},
		["paragraph_spacing"] = 1.5,
		["rotation_mode"] = 0,
		["settings"] = {
			["name"] = "PDF-Widescreen",
		},
	},
}
