-- /home/aditya/.config/koreader/settings/profiles.lua
return {
	["PDF-Widescreen"] = {
		["kopt_contrast"] = 1,
		["kopt_font_size"] = 1.45,
		["kopt_line_spacing"] = 1.2,
		["kopt_max_columns"] = 1,
		["kopt_page_margin"] = 0.1,
		["kopt_page_scroll"] = true,
		["kopt_quality"] = 1,
		["kopt_text_wrap"] = 0,
		["kopt_trim_page"] = "none",
		["kopt_zoom_direction"] = 7,
		["kopt_zoom_factor"] = 0.7,
		["kopt_zoom_mode_genus"] = "manual",
		["kopt_zoom_mode_type"] = "full",
		["kopt_zoom_overlap_h"] = 24,
		["kopt_zoom_overlap_v"] = 24,
		["kopt_zoom_range_number"] = -0.14864726782161,
		["rotation_mode"] = 0,
		["settings"] = {
			["name"] = "PDF-Widescreen",
			["order"] = {
				[1] = "rotation_mode",
				[2] = "kopt_text_wrap",
				[3] = "kopt_trim_page",
				[4] = "kopt_page_margin",
				[5] = "kopt_zoom_overlap_h",
				[6] = "kopt_zoom_overlap_v",
				[7] = "kopt_zoom_mode_type",
				[8] = "kopt_zoom_mode_genus",
				[9] = "kopt_zoom_range_number",
				[10] = "kopt_zoom_factor",
				[11] = "kopt_zoom_direction",
				[12] = "kopt_page_scroll",
				[13] = "kopt_line_spacing",
				[14] = "kopt_font_size",
				[15] = "kopt_contrast",
				[16] = "kopt_quality",
				[17] = "kopt_max_columns",
			},
		},
	},
}
